# Generated by Django 3.0.6 on 2020-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drafts',
            field=models.BooleanField(default=True),
        ),
    ]
